name: 🚀 Create Release
description: Request a GitHub release with human-readable notes (version auto-detected by @copilot)
title: "Create Release"
labels: ["release-proposal"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Task: Create GitHub Release
        
        Use this template to manually request a GitHub release. When you assign this issue to **@copilot**, 
        it will follow the [Release Process guidelines](https://github.com/DrozmotiX/ioBroker-Copilot-Instructions/blob/main/.github/copilot-instructions.md#release-process) to:
        
        1. **Automatically detect the latest version** from git tags
        2. **Determine the version type** (patch, minor, or major)
        3. **Extract all relevant changelog data** from CHANGELOG.md
        4. **Create a human-readable summary** following repository guidelines
        5. **Create the GitHub release** with the summary
        
        **Process Notes:**
        - Minor/major releases are typically created automatically via workflow
        - Patch releases can be initiated manually using this template
        - @copilot will detect version and type automatically from git tags
        - Summaries MUST follow guidelines: review and consolidate, NOT copy/paste
        
        ---
        
        ## 📝 Optional: Additional Release Context
        
        If you want to provide additional context for the release notes (optional):

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: |
        Provide any additional information that should be included in the release notes.
        This is completely optional - @copilot will create comprehensive release notes without this.
      placeholder: |
        Examples:
        - Special migration notes
        - Breaking change details
        - Important warnings or deprecations
        - Links to related documentation
      render: markdown
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## ✍️ Instructions for @copilot
        
        When this issue is assigned to you, follow the **Release Process** guidelines from 
        [.github/copilot-instructions.md](https://github.com/DrozmotiX/ioBroker-Copilot-Instructions/blob/main/.github/copilot-instructions.md#release-process):
        
        ### Step 1: Detect Version and Type
        1. Check the latest merged tags to main branch:
           ```bash
           git tag --sort=-v:refname | head -5
           ```
        2. Check existing GitHub releases to see which tags already have releases:
           ```bash
           gh release list --limit 10
           ```
        3. Identify the most recent version tag **that does not yet have a GitHub release** and determine type:
           - **Minor release** (x.Y.0): Must summarize ALL patch version release notes since last minor
           - **Major release** (X.0.0): Must summarize ALL minor release notes since last major
           - **Patch release** (x.y.Z): Can be initiated manually, summarize changes since last release notes
        
        ### Step 2: Extract Changelog Data
        Run the changelog extraction script to get all relevant entries:
        ```bash
        ./scripts/generate-release-notes.sh [DETECTED_VERSION]
        ```
        
        ### Step 3: Create Human-Readable Summary (CRITICAL REQUIREMENTS)
        
        **Follow these mandatory guidelines from copilot-instructions.md:**
        
        #### For Minor Releases:
        - ✅ MUST contain a summary of ALL changelog items from ALL patch version bumps since last minor, including merges without a release
        - ❌ Do NOT copy/paste the changelog entries
        - ✅ Review and create human-friendly summarized content
        - ⚠️ Avoid conflicts: e.g., if v0.5.4 solves an issue introduced in v0.5.2, don't mention the original issue
        
        #### For Major Releases:
        - ✅ MUST contain a summary of ALL changelog items from ALL minor/patch version bumps since last major, including merges without a release
        - ❌ Do NOT copy/paste the changelog entries
        - ✅ Review and create human-friendly summarized content
        - ⚠️ Consolidate related changes across minors into coherent themes
        
        #### For Patch Releases:
        - ✅ Summarize changelog items between last release notes and all version bumps starting from last major/minor release
        - ❌ Do NOT copy/paste the changelog entries
        - ⚠️ Handle conflicts properly: if later patches fix issues from earlier patches, consolidate appropriately
        
        ### Step 4: Create GitHub Release
        ```bash
        gh release create v[VERSION] --title "Release [VERSION]" --notes "[your human-readable summary]"
        ```
        
        ### Expected Release Note Format:
        ```markdown
        ## What's New in v[VERSION]
        
        [2-3 paragraph human-readable summary that explains the overall theme,
        purpose, and impact of this release. Write for non-technical users.]
        
        ### Key Improvements
        - [Major theme 1: consolidate related features/fixes]
        - [Major theme 2: group similar enhancements]
        - [Major theme 3: highlight important changes]
        
        ### Version Range
        This release includes changes from v[START] through v[END].
        
        ---
        Full changelog: [CHANGELOG.md](https://github.com/DrozmotiX/ioBroker-Copilot-Instructions/blob/main/CHANGELOG.md)
        ```
        
        ### Step 5: Report Completion
        Reply to this issue with:
        - Version number and type
        - Link to the created GitHub release
        - Brief summary of included version range
        - Confirmation of guideline compliance
        
        ---
        
        **For Maintainers**: After creating this issue, assign it to `@copilot` to process according to 
        [Release Process guidelines](https://github.com/DrozmotiX/ioBroker-Copilot-Instructions/blob/main/.github/copilot-instructions.md#release-process).
